### ISSUE TITLE
V2 checklist

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/OpenJSCAD.org#419]
Before being able to merge V2 into master (when we get there) we need to validate the following checklist

V2 is a major overhaul of both the geometric core, common code & ui 
* side effects (http, file system, dom) are now clear , seperate entities
* require() support for client side is fully working & tested
* combines / upgrades the web ui with the desktop advances (amongst other things)
   * updated 3D viewer
   * keyboard shortcuts
   * modules support
   * allow multiple instances of jscad per page easilly
   * very simple api for embeding a jscad instance
   * completely restructured internals
   * maximized reuse of code between uis
   * lots more !!

## geometric kernel
 - [x] use of csg V2 with all that it implies (and eliminate old CSG)

## io
- [X] updated ALL IO to use csg V2 after the above is done (lots of work)
  - [X] AMF : deserializer DONE, serializer DONE
  - [X] DXF : deserializer DONE, serializer DONE
  - [X] GCODE : deserializer DROP
  - [X] JSON : deserializer DONE, serializer DONE
  - [X] OBJ : deserializer DONE
  - SCAD : deserializer DO NOT FIX, waiting for someone to own this
  - [X] STL : deserializer DONE, serializer DONE
  - [X] SVG : deserializer DONE, serializer DONE
  - [X] X3D : serializer DONE

## common / core
 - [X] create arrayUtils and refactor
 - [X] vtree needs to be updated for V2

### inputs
- [x] drag and drop of files
- [x] drag and drop of folders
- [X] loading of remote files
- [X] conversion of files
- [x] require support , injection of explicit api
- [x] require support , geometry caching 
- [x] require support relative paths
- [X] require support node_modules (DONE via #587)
- [x] require support single file
- [x] file watcher/autoreload for single file
- [x] file watcher/autoreload for folders
- [x] examples
- [x] virtual fs module injection ie allow const fs = require('fs') in the browser

### outputs
- [x] save/export of files using v2 api

### error handling
- [x] fix unhandled and explicit error handling
- [x] make error handling from different sources coherent (web worker, http requests etc)
- [x] fix handling of http request errors 4xx
- [x] fix handling of http request errors (all)

### 3D viewer
- [x] 3d viewer basics
- [ ] zoom to fit settable
- [x] no resetting of camera to previous state
- [x] all 3D viewer instances should behave independently
- [x] improve rendering of 2d lines (no lighting)

### code editor
- [x] code editor basics

### ui
- [x] shortcuts : settable
- [x] theming

## general
- [x] migrate examples to new API
- [x] translations
- [x] multiple instances per page
- [x] coherent input/outputs handling
- [x] correct timeout and geometry generation cancellation
- [ ] correct error displaying

## tests
- [ ] side effects

## docs
- [X] document generation from jsdoc strings in code
- [X] document modeling API
- [X] document examples
- [X] document how to convert V1 to V2
 
## final checklist if all the above is done
- [X] works in latest Chrome
- [X] works in latest Firefox
- [X] works in latest Safari
- [X] works in latest Edge
- [X] works on mobile; iOS and Android devices
- [X] works on Windows 10
- [X] works on MacOS
- [X] works on Linux
- [X] proxy

closes #119 
closes #137 
closes #167 
closes #235 
closes #245 
closes #321 
closes #327 
closes #336 
closes #343 
closes #344 
closes #364 
closes #378

**Comment by kaosat-dev** [comment]
while integrating the new CSG V2 , a few questions/ issues also popped up:
- what namespacing are we going to use ?
  ie ```const jscad = require('@jscad/modeling')``` or something else ?
- no more vtree

- primitives resolution too low (wayyy too low)
- missing ability to use single floats that get expanded into arrays for size & co
- no diameter input for circle
- translate message for missing axis
  * 'offsets' is not clear, nor whether it is translate or not
  * not logical for 2d translate, forces 3 axes
    * we should fill in last axis to 0 if not passed

- cylinder : no way to use radius or diameter ! (only start/end stuff)

**Comment by z3dev** [comment]
Here’s another list of issues / questions.

1. Should ‘color’ be ‘colors’

**Comment by z3dev** [comment]
> * 'offsets' is not clear, nor whether it is translate or not

Actually, offsets is an array. So that’s correct. But the example is wrong. :(

**Comment by kaosat-dev** [comment]
const {sin, cos, tan, sqrt, lookup} = require('${apiMainPath}').maths => I need to double check but lookup is missing and might be needed ?

**Comment by z3dev** [comment]
> const {sin, cos, tan, sqrt, lookup} = require('${apiMainPath}').maths => I need to double check but lookup is missing and might be needed ?

Why? For SCAD compatibility? We decided to break from SCAD and CSG APIs.

**Comment by kaosat-dev** [comment]
I still do not understand why you mention SCAD regularly ? I only view things as 'what parts of any previous API was useful', not where/how/what it came from.

I meant the lookup function specifically : it is used in at least a few examples, and might (emphasis on might) still be useful for some people

**Comment by kaosat-dev** [comment]
math => maths (plural is the standard as far as I know)

**Comment by kaosat-dev** [comment]
> Here’s another list of issues / questions.
> 
> 1. Should ‘modeling/color’ be ‘colors’
> 2. Should ‘modeling/geometry’ be ‘geometries’
I think in both cases I think the current naming is fine and the best option to be honest :)

**Comment by kaosat-dev** [comment]
> Actually, offsets is an array. So that’s correct. But the example is wrong. :(

I do not understand sorry ?

**Comment by kaosat-dev** [comment]
@z3dev I updated (with all latest obervations) & cleaned up the long long list above, added checkboxes

**Comment by z3dev** [comment]
> > 1. Should ‘modeling/color’ be ‘colors’
> > 2. Should ‘modeling/geometry’ be ‘geometries’
> 
> I think in both cases I think the current naming is fine and the best option to be honest :)

I’m fine. But let’s be consistent and keep ‘math’. I think this is the best option. :)

**Comment by z3dev** [comment]
> while integrating the new CSG V2 , a few questions/ issues also popped up:

Nice list. How about integrating these into the large list above?
I’d like to open Issues for some of the smaller tasks as well.

**Comment by z3dev** [comment]
browser list for desktops / laptops... shouldn't IE be included?

**Comment by z3dev** [comment]
We need to pull items from these issues

jscad/io#64

**Comment by kaosat-dev** [comment]
I can move some of those to here , makes sense
Big question: should we close some issues despite not having a "final V2 release" yet ? (what we seem to be heading to is more of a 'rolling release' which is better imho ?)

**Comment by z3dev** [comment]
> Big question: should we close some issues despite not having a "final V2 release" yet ?

I think this makes sense, especially if there’s a specific test for the issue. This will make issue management easier, as well as the releases.

**Comment by kaosat-dev** [comment]
@z3dev please, do not delete my comments, it makes the conversation harder to follow, as I do not know what, or why was deleted, thanks :)

**Comment by kaosat-dev** [comment]
about **pipe()** , I found that as soon as you have more than two operands being chained/wrapping, it makes code considerably more readable:

```javascript
const lotsOfOps = pipe(
  union(transformedRectangle, movedEllipse),
  translate([1, 0, 0]),
  centerAt([10, -25, 0]),
  translate([2, 0, 0]),
  scale([1, 2, 1]),
  color([1, 0, 0, 0.5])
)

// without pipe
const lotsOfOpsOld = color([1, 0, 0, 0.5],
  scale([1, 2, 1],
    translate([2, 0, 0],
      centerAt([10, -25, 0],
        translate([1, 0, 0],
          union(transformedRectangle, movedEllipse)
        ))))
)
```

**Comment by z3dev** [comment]
@garrlker How about taking something from the second list? There are some small changes to API functions, additional tests to create, etc.

**Comment by garrlker** [comment]
@z3dev Sure,

I'll take a couple from the 'Primitives' list.

Like `circle : no diameter option` and `cylinder : no radius or diameter option, only start/end radius`.

I'll check if an issue is already created for either, if not I'll make my own.

**Comment by z3dev** [comment]
> I'll take a couple from the 'Primitives' list.
> 
> Like `circle : no diameter option` and `cylinder : no radius or diameter option, only start/end radius`.

Cool. FYI, I’m working on the IO modules currently. We should not overlap. :)

**Comment by z3dev** [comment]
FYI, I'm creating a couple of WIKI pages for Early Adopters of V2. A lot has changes some a little documentation can go a long way.

https://openjscad.org/dokuwiki/doku.php?id=early_v2

**Comment by udif** [comment]
Is https://jscad.xyz/ reflecting current V2 code?
Is it possible to add a CI job to build v2 on github pages?
I use v1 on the web almost exclusively because it lets me share links with my designs for other people to look at without forcing them to install anything.

**Comment by z3dev** [comment]
> Is https://jscad.xyz/ reflecting current V2 code?

Not yet. Early adopters need to clone this repository.

> Is it possible to add a CI job to build v2 on github pages?

O job?
One of the remaining  tasks is to create an automated release and distribution script.

**Comment by hrgdavor** [comment]
I tried the steps from the wiki and both on windows and Debian linux

I tried packages/web

 npm run dev

> @jscad/web@1.10.0 dev /opt/OpenJSCAD.org/packages/web
> budo demo.js --port=8081 --css demo.css --live -- -b

[0000] info  Server running at http://136.243.90.99:8081/ (connect)
[0000] info  LiveReload running
Error: Cannot find module 'most' from
'/opt/OpenJSCAD.org/packages/web/src/sideEffects/state'
    at
/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process
(/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir
(/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load
(/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex
(/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at
/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:166:21) {
  stream: [Labeled]
}

**Comment by z3dev** [comment]
UG... please follow the early adopter document, and open a new issue. This is a specific thread for V2 checklist, not for issues.

**Comment by z3dev** [comment]
> @garrlker How about taking something from the second list? There are some small changes to API functions, additional tests to create, etc.

@garrlker any progress on these changes? any issues?

**Comment by z3dev** [comment]
@kaosat-dev we have discussed this before but this is really weird...

**const color = require('@jscad/modeling').color.color feels very odd**

I totally agree, but what’s the correct namespace? Do we only expect colors? What about shades? Or textures?

**Comment by kaosat-dev** [comment]
gaah, I thought I had replied !
@z3dev the only thing I see is changing the namespace to colors (plural), then It is slightly less odd
I also like the plural because there are multiple color related functions ? (just like I favor maths as plural :D )

**Comment by crysislinux** [comment]
@kaosat-dev @z3dev what's the best practice for chaining now? It's ok but feels a bit weird when having more than three transformation functions chained.

**Comment by z3dev** [comment]
Closing as V2 JSCAD has been released.

Any outstanding tasks have been converted to issues.
